"""Store resource provider for MCP

Exposes named graphs in the RDF store as MCP resources.
Allows agents to inspect intermediate graphs generated during query execution.
"""

import logging
from typing import List
from urllib.parse import quote, unquote
from mcp.types import Resource
from rdflib import URIRef, Namespace

from SPARQLLM.udf.SPARQLLM import store

logger = logging.getLogger("SPARQLLM.mcp.resources.store")

# Namespaces for metadata extraction
PROV = Namespace("http://www.w3.org/ns/prov#")
RDFS = Namespace("http://www.w3.org/2000/01/rdf-schema#")
SCHEMA = Namespace("http://schema.org/")


async def list_store_resources(session_id: str) -> List[Resource]:
    """
    List all named graphs in the store as MCP resources.

    Args:
        session_id: Current session identifier

    Returns:
        List of Resource objects with metadata
    """
    resources = []

    try:
        # Iterate all named graphs in the store
        graph_count = 0
        for context in store.contexts():
            # Skip default graph
            if context.identifier == URIRef("urn:x-rdflib:default"):
                continue

            graph_count += 1
            graph_id = str(context.identifier)
            encoded_graph_id = quote(graph_id, safe='')
            resource_uri = f"store://{session_id}/graphs/{encoded_graph_id}"

            # Extract metadata from graph
            name = extract_graph_name(context)
            description = extract_graph_description(context)

            resources.append(
                Resource(
                    uri=resource_uri,
                    name=name,
                    description=description,
                    mimeType="application/ld+json"
                )
            )

        logger.info(f"Listed {len(resources)} graph resources (total graphs: {graph_count})")

    except Exception as e:
        logger.error(f"Error listing resources: {e}", exc_info=True)
        # Return empty list on error rather than failing
        return []

    return resources


def extract_graph_name(context) -> str:
    """
    Extract human-readable name from graph metadata.

    Tries:
    1. RDFS label
    2. Schema.org name
    3. Last part of graph identifier

    Args:
        context: RDFLib graph context

    Returns:
        Human-readable name
    """
    # Try RDFS label
    for _, _, label in context.triples((context.identifier, RDFS.label, None)):
        return str(label)

    # Try schema:name
    for _, _, name in context.triples((context.identifier, SCHEMA.name, None)):
        return str(name)

    # Fallback: extract from graph identifier
    graph_id = str(context.identifier)

    if graph_id.startswith("urn:uuid:"):
        # Shorten UUID: use last 12 chars
        return f"Graph {graph_id[-12:]}"
    elif "/" in graph_id:
        # Use last path component
        return graph_id.split("/")[-1]
    elif "#" in graph_id:
        # Use fragment
        return graph_id.split("#")[-1]

    return graph_id


def extract_graph_description(context) -> str:
    """
    Extract description from graph metadata.

    Tries:
    1. PROV-O generation time
    2. PROV-O generating activity
    3. RDFS comment
    4. Triple count

    Args:
        context: RDFLib graph context

    Returns:
        Description string
    """
    # Look for PROV-O generatedAtTime
    for _, _, timestamp in context.triples((context.identifier, PROV.generatedAtTime, None)):
        return f"Generated at {timestamp}"

    # Look for PROV-O wasGeneratedBy
    for _, _, activity in context.triples((context.identifier, PROV.wasGeneratedBy, None)):
        activity_str = str(activity)
        # Extract function name from URI
        if "ggf" in activity_str or "example.org" in activity_str:
            func_name = activity_str.split("/")[-1].split("#")[-1]
            return f"Generated by {func_name}"
        return f"Generated by {activity_str}"

    # Look for RDFS comment
    for _, _, comment in context.triples((context.identifier, RDFS.comment, None)):
        return str(comment)

    # Fallback: triple count
    triple_count = len(context)
    return f"Named graph with {triple_count} triple{'s' if triple_count != 1 else ''}"


async def read_store_resource(uri: str, session_id: str) -> str:
    """
    Read graph content as JSON-LD.

    Args:
        uri: Resource URI (e.g., store://sess-123/graphs/urn%3Auuid%3A456)
        session_id: Current session ID for validation

    Returns:
        JSON-LD serialization of graph

    Raises:
        ValueError: If URI is invalid or graph not found
    """
    # Convert AnyUrl to string if needed
    uri_str = str(uri)

    # Validate URI format
    prefix = f"store://{session_id}/graphs/"
    if not uri_str.startswith(prefix):
        raise ValueError(
            f"Invalid resource URI: {uri_str}. "
            f"Expected format: store://{session_id}/graphs/{{graph_id}}"
        )

    # Extract and decode graph ID
    encoded_graph_id = uri_str[len(prefix):]
    graph_id = unquote(encoded_graph_id)

    logger.info(f"Reading graph resource: {graph_id}")

    try:
        # Find graph in store
        graph_uri = URIRef(graph_id)
        context = store.get_context(graph_uri)

        if context is None or len(context) == 0:
            raise ValueError(f"Graph not found or empty: {graph_id}")

        # Serialize to JSON-LD
        jsonld_bytes = context.serialize(format="json-ld", indent=2)

        # Handle both str and bytes return types from rdflib
        if isinstance(jsonld_bytes, bytes):
            jsonld_str = jsonld_bytes.decode("utf-8")
        else:
            jsonld_str = jsonld_bytes

        logger.info(
            f"Graph serialized successfully: {len(jsonld_str)} bytes, "
            f"{len(context)} triples"
        )

        return jsonld_str

    except Exception as e:
        logger.error(f"Error reading resource: {e}", exc_info=True)
        raise ValueError(f"Failed to read graph {graph_id}: {str(e)}")
